name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.102'  

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release --no-restore

      - name: Run unit tests
        run: dotnet test --no-restore --verbosity normal

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.102'  

      - name: Restore dependencies
        run: dotnet restore

      - name: Set Environment Variables
        run: |
          echo "DATABASE_CONNECTION=${{ secrets.DATABASE_CONNECTION }}" >> $GITHUB_ENV
          echo "JWT_KEY=${{ secrets.JWT_KEY }}" >> $GITHUB_ENV
          echo "JWT_ISSUER=${{ secrets.JWT_ISSUER }}" >> $GITHUB_ENV
          echo "SMTP_SERVER=${{ secrets.SMTP_SERVER }}" >> $GITHUB_ENV
          echo "SMTP_USERNAME=${{ secrets.SMTP_USERNAME }}" >> $GITHUB_ENV
          echo "SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}" >> $GITHUB_ENV

      - name: Publish Application
        run: |
          export DATABASE_CONNECTION="${{ secrets.DATABASE_CONNECTION }}"
          export JWT_KEY="${{ secrets.JWT_KEY }}"
          export JWT_ISSUER="${{ secrets.JWT_ISSUER }}"
          export SMTP_SERVER="${{ secrets.SMTP_SERVER }}"
          export SMTP_USERNAME="${{ secrets.SMTP_USERNAME }}"
          export SMTP_PASSWORD="${{ secrets.SMTP_PASSWORD }}"
          dotnet publish -c Release -o ./publish

      # before viva
      # - name: Deploy to Azure
      #   uses: azure/webapps-deploy@v2
      #   with:
      #     app-name: "YourAppName"
      #     publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
      #     package: ./publish
